### ISSUE TITLE
issubclass() error when running the example

### ISSUE THREAD

**Issue by braceal** [ramanathanlab/deepdrivemd#15]
**Describe the bug**
The test example does not work and produces this error:
```console
Traceback (most recent call last):
  File "/homes/b316714/anaconda3/envs/deepdrivemd/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/homes/b316714/anaconda3/envs/deepdrivemd/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/lambda_stor/homes/b316714/deepdrivemd/deepdrivemd/workflows/openmm_cvae.py", line 37, in <module>
    from deepdrivemd.parsl import ComputeSettingsTypes
  File "/lambda_stor/homes/b316714/deepdrivemd/deepdrivemd/parsl.py", line 12, in <module>
    class BaseComputeSettings(BaseSettings, ABC):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/homes/b316714/anaconda3/envs/deepdrivemd/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**To Reproduce**
Follow the install instructions in the README: 
```console
conda create -n deepdrivemd python=3.9 -y
conda activate deepdrivemd
conda install -c conda-forge gcc=12.1.0 -y
conda install -c conda-forge openmm -y
git clone https://github.com/ramanathanlab/deepdrivemd.git
cd deepdrivemd
make install
```
Then run this example, 
```console
python -m deepdrivemd.workflows.openmm_cvae -c tests/apps-enabled-workstation/test.yaml
```

**Comment by braceal** [comment]
This bug will be fixed in the next release and has been tracked back to the current pinned version of parsl==2023.3.13 which does not have correct version pins for `typegaurd` and `typing_extensions` https://github.com/Parsl/parsl/blob/2023.03.13/requirements.txt

In the meantime, running these commands will fix the error:
```
pip install typing_extensions==4.4.0
pip install typeguard==2.13.3
```
